Repository jenkinsci/appcenter-plugin, pull requests merged in 2019-11, with the labels that each got.

#39 [JENKINS-60027] Use system dependent separator character
  src/test/java/io/jenkins/plugins/appcenter/task/internal/CheckFileExistsTaskTest.java
Labels: bug

#38 [JENKINS-59942] Add stats badges to README
  README.md
Labels: documentation

#40 [JENKINS-59694] When build step fails or get aborted upload is still tried
  src/main/java/io/jenkins/plugins/appcenter/AppCenterRecorder.java
  src/main/resources/io/jenkins/plugins/appcenter/Messages.properties
Labels: bug

#37 [JENKINS-58490] Support symbol files
  pom.xml
  src/main/java/io/jenkins/plugins/appcenter/AppCenterRecorder.java
  src/main/java/io/jenkins/plugins/appcenter/api/AppCenterService.java
  src/main/java/io/jenkins/plugins/appcenter/api/UploadService.java
  src/main/java/io/jenkins/plugins/appcenter/di/UploadModule.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/Origin.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/Status.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolType.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolUploadBeginRequest.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolUploadBeginResponse.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolUploadEndRequest.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolUploadEndResponse.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolUploadUserInfo.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/UploadedSymbolInfo.java
  src/main/java/io/jenkins/plugins/appcenter/task/UploadTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CheckFileExistsTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CommitUploadResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CreateUploadResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/PrerequisitesTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/UploadAppToResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/request/UploadRequest.java
  src/main/java/io/jenkins/plugins/appcenter/util/AndroidParser.java
  src/main/java/io/jenkins/plugins/appcenter/util/ParserFactory.java
  src/main/java/io/jenkins/plugins/appcenter/validator/PathToDebugSymbolsValidator.java
  src/main/resources/io/jenkins/plugins/appcenter/AppCenterRecorder/config.jelly
  src/main/resources/io/jenkins/plugins/appcenter/Messages.properties
  src/test/java/io/jenkins/plugins/appcenter/ConfigurationTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/CheckFileExistsTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/CommitUploadResourceTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/CreateUploadResourceTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/PrerequisitesTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/UploadAppToResourceTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/validator/PathToDebugSymbolsValidatorTest.java
Labels: feature

#41 [JENKINS-60197] Add support for MacOS files
  src/main/java/io/jenkins/plugins/appcenter/task/internal/PrerequisitesTask.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/PrerequisitesTaskTest.java
Labels: enhancement

#42 [JENKINS-60232] Add appcenter api models for error responses
  src/main/java/io/jenkins/plugins/appcenter/api/AppCenterService.java
  src/main/java/io/jenkins/plugins/appcenter/api/UploadService.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/BuildInfo.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/DestinationError.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/DestinationId.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/ErrorDetails.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/Failure.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/Origin.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/ReleaseDetailsUpdateResponse.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/ReleaseUpdateError.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/ReleaseUpdateRequest.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/ReleaseUploadBeginRequest.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/ReleaseUploadBeginResponse.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/ReleaseUploadEndRequest.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/ReleaseUploadEndResponse.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/Status.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolType.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolUpload.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolUploadBeginRequest.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolUploadBeginResponse.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolUploadEndRequest.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolUploadEndResponse.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/SymbolUploadUserInfo.java
  src/main/java/io/jenkins/plugins/appcenter/model/appcenter/UploadedSymbolInfo.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CommitUploadResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CreateUploadResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/DistributeResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/PrerequisitesTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/UploadAppToResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/request/UploadRequest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/CommitUploadResourceTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/CreateUploadResourceTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/PrerequisitesTaskTest.java
Labels: internal
