Repository jenkinsci/appcenter-plugin, pull requests merged in 2019-10, with the labels that each got.

#32 [JENKINS-59860] Migrate to GitHub for documentation
  .github/release-drafter.yml
  README.md
  pom.xml
Labels: documentation

#29 [JENKINS-59528] Support Ant style file paths
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CheckFileExistsTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/UploadAppToResourceTask.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/CheckFileExistsTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/UploadAppToResourceTaskTest.java
Labels: enhancement

#33 [JENKINS-59944] Remove unused exception constructors
  src/main/java/io/jenkins/plugins/appcenter/AppCenterException.java
Labels: enhancement

#34 [JENKINS-59945] Add AppCenterLogger interface
  src/main/java/io/jenkins/plugins/appcenter/AppCenterLogger.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CheckFileExistsTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CommitUploadResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CreateUploadResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/DistributeResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/UploadAppToResourceTask.java
Labels: internal

#35 [JENKINS-59946] Create upload requests via Builder
  src/main/java/io/jenkins/plugins/appcenter/di/UploadModule.java
  src/main/java/io/jenkins/plugins/appcenter/task/request/UploadRequest.java
Labels: internal

#36 [JENKINS-59947] Remove inner request classes
  src/main/java/io/jenkins/plugins/appcenter/task/UploadTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/AppCenterTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CheckFileExistsTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CommitUploadResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/CreateUploadResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/DistributeResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/UploadAppToResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/task/request/UploadRequest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/CheckFileExistsTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/CommitUploadResourceTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/CreateUploadResourceTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/DistributeResourceTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/UploadAppToResourceTaskTest.java
Labels: internal
