Repository jenkinsci/appcenter-plugin, pull requests merged in 2020-11, with the labels that each got.

#52 [JENKINS-61337] Implemented uploading of symbols > 256mb via Azure SDK
  pom.xml
  src/main/java/io/jenkins/plugins/appcenter/api/AppCenterServiceFactory.java
  src/main/java/io/jenkins/plugins/appcenter/task/internal/UploadAppToResourceTask.java
  src/main/java/io/jenkins/plugins/appcenter/util/RemoteFileUtils.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/UploadAppToResourceTaskTest.java
  src/test/java/io/jenkins/plugins/appcenter/util/TestFileUtil.java
Labels: enhancement

#58 [JENKINS-64188] Replace Netty with OkHttp
  pom.xml
  src/main/java/io/jenkins/plugins/appcenter/api/AppCenterServiceFactory.java
  src/test/java/io/jenkins/plugins/appcenter/task/internal/UploadAppToResourceTaskTest.java
Labels: internal

#59 [JENKINS-64259] Add Kotlin as a main dependency
  pom.xml
Labels: bug
